version: '2'
services:
  server:
    container_name: starter_server
    build:
      context: ./server
      args:
        username: ${WILDFLY_USERNAME}
        password: ${WILDFLY_PASSWORD}
    ports:
      - "${SERVER_PORT_WEB}:8080"
      - "${SERVER_PORT_ADMIN}:9990"
    command: /opt/jboss/wildfly/bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0


  maven:
    container_name: starter_maven
    image: maven:3.3.9-jdk-8-alpine
    volumes:
      - "../:/home/code"
    working_dir: /home/code
    command: mvn clean -Dwildfly.hostname=server -Dwildfly.username=${WILDFLY_USERNAME} -Dwildfly.password=${WILDFLY_PASSWORD} wildfly:deploy
    depends_on:
      - server